GET http://localhost:3010/cars HTTP/1.1

###

GET http://localhost:3010/cars/1 HTTP/1.1

###

POST http://localhost:3010/cars HTTP/1.1
Content-Type: application/json

{
    "make": "Tesla",
    "model": "S",
    "year": 2018,
    "color": "red",
    "price": 125000
  }

###

PUT http://localhost:3010/cars/2 HTTP/1.1
Content-Type: application/json

{
    "make": "Tesla",
    "model": "T",
    "year": 2018,
    "color": "red",
    "price": 125000,
    "id": 2
  }

###

DELETE http://localhost:3010/cars/3 HTTP/1.1
